export type RevelationPlace = 'makkah' | 'madinah';

export interface SurahMetaEntry {
  number: number;
  name_arabic: string;
  name_english: string;
  name_urdu: string;
  ayah_count: number;
  revelation_place: RevelationPlace;
}

export const SURAH_META: SurahMetaEntry[] = [
  { number: 1,   name_arabic: 'الفاتحة',       name_english: 'Al-Fatihah',     name_urdu: 'الفاتحہ',       ayah_count: 7,   revelation_place: 'makkah' },
  { number: 2,   name_arabic: 'البقرة',        name_english: 'Al-Baqarah',     name_urdu: 'البقرہ',        ayah_count: 286, revelation_place: 'madinah' },
  { number: 3,   name_arabic: 'آل عمران',      name_english: 'Aal-E-Imran',    name_urdu: 'آل عمران',      ayah_count: 200, revelation_place: 'madinah' },
  { number: 4,   name_arabic: 'النساء',        name_english: 'An-Nisa',        name_urdu: 'النساء',        ayah_count: 176, revelation_place: 'madinah' },
  { number: 5,   name_arabic: 'المائدة',       name_english: 'Al-Maidah',      name_urdu: 'المائدہ',       ayah_count: 120, revelation_place: 'madinah' },
  { number: 6,   name_arabic: 'الأنعام',       name_english: 'Al-Anam',        name_urdu: 'الأنعام',       ayah_count: 165, revelation_place: 'makkah' },
  { number: 7,   name_arabic: 'الأعراف',       name_english: 'Al-Araf',        name_urdu: 'الأعراف',       ayah_count: 206, revelation_place: 'makkah' },
  { number: 8,   name_arabic: 'الأنفال',       name_english: 'Al-Anfal',       name_urdu: 'الأنفال',       ayah_count: 75,  revelation_place: 'madinah' },
  { number: 9,   name_arabic: 'التوبة',        name_english: 'At-Tawbah',      name_urdu: 'التوبہ',        ayah_count: 129, revelation_place: 'madinah' },
  { number: 10,  name_arabic: 'يونس',          name_english: 'Yunus',          name_urdu: 'يونس',          ayah_count: 109, revelation_place: 'makkah' },
  { number: 11,  name_arabic: 'هود',           name_english: 'Hud',            name_urdu: 'ھود',           ayah_count: 123, revelation_place: 'makkah' },
  { number: 12,  name_arabic: 'يوسف',          name_english: 'Yusuf',          name_urdu: 'يوسف',          ayah_count: 111, revelation_place: 'makkah' },
  { number: 13,  name_arabic: 'الرعد',         name_english: 'Ar-Rad',         name_urdu: 'الرعد',         ayah_count: 43,  revelation_place: 'madinah' },
  { number: 14,  name_arabic: 'إبراهيم',       name_english: 'Ibrahim',        name_urdu: 'إبراہيم',       ayah_count: 52,  revelation_place: 'makkah' },
  { number: 15,  name_arabic: 'الحجر',         name_english: 'Al-Hijr',        name_urdu: 'الحجر',         ayah_count: 99,  revelation_place: 'makkah' },
  { number: 16,  name_arabic: 'النحل',         name_english: 'An-Nahl',        name_urdu: 'النحل',         ayah_count: 128, revelation_place: 'makkah' },
  { number: 17,  name_arabic: 'الإسراء',       name_english: 'Al-Isra',        name_urdu: 'الإسراء',       ayah_count: 111, revelation_place: 'makkah' },
  { number: 18,  name_arabic: 'الكهف',         name_english: 'Al-Kahf',        name_urdu: 'الكہف',         ayah_count: 110, revelation_place: 'makkah' },
  { number: 19,  name_arabic: 'مريم',          name_english: 'Maryam',         name_urdu: 'مريم',          ayah_count: 98,  revelation_place: 'makkah' },
  { number: 20,  name_arabic: 'طه',            name_english: 'Taha',           name_urdu: 'طہ',            ayah_count: 135, revelation_place: 'makkah' },
  { number: 21,  name_arabic: 'الأنبياء',      name_english: 'Al-Anbiya',      name_urdu: 'الأنبياء',      ayah_count: 112, revelation_place: 'makkah' },
  { number: 22,  name_arabic: 'الحج',          name_english: 'Al-Hajj',        name_urdu: 'الحج',          ayah_count: 78,  revelation_place: 'madinah' },
  { number: 23,  name_arabic: 'المؤمنون',      name_english: 'Al-Muminun',     name_urdu: 'المؤمنون',      ayah_count: 118, revelation_place: 'makkah' },
  { number: 24,  name_arabic: 'النور',         name_english: 'An-Nur',         name_urdu: 'النور',         ayah_count: 64,  revelation_place: 'madinah' },
  { number: 25,  name_arabic: 'الفرقان',       name_english: 'Al-Furqan',      name_urdu: 'الفرقان',       ayah_count: 77,  revelation_place: 'makkah' },
  { number: 26,  name_arabic: 'الشعراء',       name_english: 'Ash-Shuara',     name_urdu: 'الشعراء',       ayah_count: 227, revelation_place: 'makkah' },
  { number: 27,  name_arabic: 'النمل',         name_english: 'An-Naml',        name_urdu: 'النمل',         ayah_count: 93,  revelation_place: 'makkah' },
  { number: 28,  name_arabic: 'القصص',         name_english: 'Al-Qasas',       name_urdu: 'القصص',         ayah_count: 88,  revelation_place: 'makkah' },
  { number: 29,  name_arabic: 'العنكبوت',      name_english: 'Al-Ankabut',     name_urdu: 'العنكبوت',      ayah_count: 69,  revelation_place: 'makkah' },
  { number: 30,  name_arabic: 'الروم',         name_english: 'Ar-Rum',         name_urdu: 'الروم',         ayah_count: 60,  revelation_place: 'makkah' },
  { number: 31,  name_arabic: 'لقمان',         name_english: 'Luqman',         name_urdu: 'لقمان',         ayah_count: 34,  revelation_place: 'makkah' },
  { number: 32,  name_arabic: 'السجدة',        name_english: 'As-Sajdah',      name_urdu: 'السجدہ',        ayah_count: 30,  revelation_place: 'makkah' },
  { number: 33,  name_arabic: 'الأحزاب',       name_english: 'Al-Ahzab',       name_urdu: 'الأحزاب',       ayah_count: 73,  revelation_place: 'madinah' },
  { number: 34,  name_arabic: 'سبأ',           name_english: 'Saba',           name_urdu: 'سبأ',           ayah_count: 54,  revelation_place: 'makkah' },
  { number: 35,  name_arabic: 'فاطر',          name_english: 'Fatir',          name_urdu: 'فاطر',          ayah_count: 45,  revelation_place: 'makkah' },
  { number: 36,  name_arabic: 'يس',            name_english: 'Ya-Sin',         name_urdu: 'يس',            ayah_count: 83,  revelation_place: 'makkah' },
  { number: 37,  name_arabic: 'الصافات',       name_english: 'As-Saffat',      name_urdu: 'الصافات',       ayah_count: 182, revelation_place: 'makkah' },
  { number: 38,  name_arabic: 'ص',             name_english: 'Sad',            name_urdu: 'ص',             ayah_count: 88,  revelation_place: 'makkah' },
  { number: 39,  name_arabic: 'الزمر',         name_english: 'Az-Zumar',       name_urdu: 'الزمر',         ayah_count: 75,  revelation_place: 'makkah' },
  { number: 40,  name_arabic: 'غافر',          name_english: 'Ghafir',         name_urdu: 'غافر',          ayah_count: 85,  revelation_place: 'makkah' },
  { number: 41,  name_arabic: 'فصلت',          name_english: 'Fussilat',       name_urdu: 'فصلت',          ayah_count: 54,  revelation_place: 'makkah' },
  { number: 42,  name_arabic: 'الشورى',        name_english: 'Ash-Shura',      name_urdu: 'الشورى',        ayah_count: 53,  revelation_place: 'makkah' },
  { number: 43,  name_arabic: 'الزخرف',        name_english: 'Az-Zukhruf',     name_urdu: 'الزخرف',        ayah_count: 89,  revelation_place: 'makkah' },
  { number: 44,  name_arabic: 'الدخان',        name_english: 'Ad-Dukhan',      name_urdu: 'الدخان',        ayah_count: 59,  revelation_place: 'makkah' },
  { number: 45,  name_arabic: 'الجاثية',       name_english: 'Al-Jathiyah',    name_urdu: 'الجاثيہ',       ayah_count: 37,  revelation_place: 'makkah' },
  { number: 46,  name_arabic: 'الأحقاف',       name_english: 'Al-Ahqaf',       name_urdu: 'الأحقاف',       ayah_count: 35,  revelation_place: 'makkah' },
  { number: 47,  name_arabic: 'محمد',          name_english: 'Muhammad',       name_urdu: 'محمد',          ayah_count: 38,  revelation_place: 'madinah' },
  { number: 48,  name_arabic: 'الفتح',         name_english: 'Al-Fath',        name_urdu: 'الفتح',         ayah_count: 29,  revelation_place: 'madinah' },
  { number: 49,  name_arabic: 'الحجرات',       name_english: 'Al-Hujurat',     name_urdu: 'الحجرات',       ayah_count: 18,  revelation_place: 'madinah' },
  { number: 50,  name_arabic: 'ق',             name_english: 'Qaf',            name_urdu: 'ق',             ayah_count: 45,  revelation_place: 'makkah' },
  { number: 51,  name_arabic: 'الذاريات',      name_english: 'Adh-Dhariyat',   name_urdu: 'الذاريات',      ayah_count: 60,  revelation_place: 'makkah' },
  { number: 52,  name_arabic: 'الطور',         name_english: 'At-Tur',         name_urdu: 'الطور',         ayah_count: 49,  revelation_place: 'makkah' },
  { number: 53,  name_arabic: 'النجم',         name_english: 'An-Najm',        name_urdu: 'النجم',         ayah_count: 62,  revelation_place: 'makkah' },
  { number: 54,  name_arabic: 'القمر',         name_english: 'Al-Qamar',       name_urdu: 'القمر',         ayah_count: 55,  revelation_place: 'makkah' },
  { number: 55,  name_arabic: 'الرحمن',        name_english: 'Ar-Rahman',      name_urdu: 'الرحمن',        ayah_count: 78,  revelation_place: 'madinah' },
  { number: 56,  name_arabic: 'الواقعة',       name_english: 'Al-Waqiah',      name_urdu: 'الواقعہ',       ayah_count: 96,  revelation_place: 'makkah' },
  { number: 57,  name_arabic: 'الحديد',        name_english: 'Al-Hadid',       name_urdu: 'الحديد',        ayah_count: 29,  revelation_place: 'madinah' },
  { number: 58,  name_arabic: 'المجادلة',      name_english: 'Al-Mujadilah',   name_urdu: 'المجادلہ',      ayah_count: 22,  revelation_place: 'madinah' },
  { number: 59,  name_arabic: 'الحشر',         name_english: 'Al-Hashr',       name_urdu: 'الحشر',         ayah_count: 24,  revelation_place: 'madinah' },
  { number: 60,  name_arabic: 'الممتحنة',      name_english: 'Al-Mumtahanah',  name_urdu: 'الممتحنہ',      ayah_count: 13,  revelation_place: 'madinah' },
  { number: 61,  name_arabic: 'الصف',          name_english: 'As-Saff',        name_urdu: 'الصف',          ayah_count: 14,  revelation_place: 'madinah' },
  { number: 62,  name_arabic: 'الجمعة',        name_english: 'Al-Jumuah',      name_urdu: 'الجمعہ',        ayah_count: 11,  revelation_place: 'madinah' },
  { number: 63,  name_arabic: 'المنافقون',     name_english: 'Al-Munafiqun',   name_urdu: 'المنافقون',     ayah_count: 11,  revelation_place: 'madinah' },
  { number: 64,  name_arabic: 'التغابن',       name_english: 'At-Taghabun',    name_urdu: 'التغابن',       ayah_count: 18,  revelation_place: 'madinah' },
  { number: 65,  name_arabic: 'الطلاق',        name_english: 'At-Talaq',       name_urdu: 'الطلاق',        ayah_count: 12,  revelation_place: 'madinah' },
  { number: 66,  name_arabic: 'التحريم',       name_english: 'At-Tahrim',      name_urdu: 'التحريم',       ayah_count: 12,  revelation_place: 'madinah' },
  { number: 67,  name_arabic: 'الملك',         name_english: 'Al-Mulk',        name_urdu: 'الملك',         ayah_count: 30,  revelation_place: 'makkah' },
  { number: 68,  name_arabic: 'القلم',         name_english: 'Al-Qalam',       name_urdu: 'القلم',         ayah_count: 52,  revelation_place: 'makkah' },
  { number: 69,  name_arabic: 'الحاقة',        name_english: 'Al-Haqqah',      name_urdu: 'الحاقہ',        ayah_count: 52,  revelation_place: 'makkah' },
  { number: 70,  name_arabic: 'المعارج',       name_english: 'Al-Maarij',      name_urdu: 'المعارج',       ayah_count: 44,  revelation_place: 'makkah' },
  { number: 71,  name_arabic: 'نوح',           name_english: 'Nuh',            name_urdu: 'نوح',           ayah_count: 28,  revelation_place: 'makkah' },
  { number: 72,  name_arabic: 'الجن',          name_english: 'Al-Jinn',        name_urdu: 'الجن',          ayah_count: 28,  revelation_place: 'makkah' },
  { number: 73,  name_arabic: 'المزمل',        name_english: 'Al-Muzzammil',   name_urdu: 'المزمل',        ayah_count: 20,  revelation_place: 'makkah' },
  { number: 74,  name_arabic: 'المدثر',        name_english: 'Al-Muddaththir', name_urdu: 'المدثر',        ayah_count: 56,  revelation_place: 'makkah' },
  { number: 75,  name_arabic: 'القيامة',       name_english: 'Al-Qiyamah',     name_urdu: 'القيامہ',       ayah_count: 40,  revelation_place: 'makkah' },
  { number: 76,  name_arabic: 'الإنسان',       name_english: 'Al-Insan',       name_urdu: 'الإنسان',       ayah_count: 31,  revelation_place: 'madinah' },
  { number: 77,  name_arabic: 'المرسلات',      name_english: 'Al-Mursalat',    name_urdu: 'المرسلات',      ayah_count: 50,  revelation_place: 'makkah' },
  { number: 78,  name_arabic: 'النبأ',         name_english: 'An-Naba',        name_urdu: 'النبأ',         ayah_count: 40,  revelation_place: 'makkah' },
  { number: 79,  name_arabic: 'النازعات',      name_english: 'An-Naziat',      name_urdu: 'النازعات',      ayah_count: 46,  revelation_place: 'makkah' },
  { number: 80,  name_arabic: 'عبس',           name_english: 'Abasa',          name_urdu: 'عبس',           ayah_count: 42,  revelation_place: 'makkah' },
  { number: 81,  name_arabic: 'التكوير',       name_english: 'At-Takwir',      name_urdu: 'التكوير',       ayah_count: 29,  revelation_place: 'makkah' },
  { number: 82,  name_arabic: 'الانفطار',      name_english: 'Al-Infitar',     name_urdu: 'الانفطار',      ayah_count: 19,  revelation_place: 'makkah' },
  { number: 83,  name_arabic: 'المطففين',      name_english: 'Al-Mutaffifin',  name_urdu: 'المطففين',      ayah_count: 36,  revelation_place: 'makkah' },
  { number: 84,  name_arabic: 'الانشقاق',      name_english: 'Al-Inshiqaq',    name_urdu: 'الانشقاق',      ayah_count: 25,  revelation_place: 'makkah' },
  { number: 85,  name_arabic: 'البروج',        name_english: 'Al-Buruj',       name_urdu: 'البروج',        ayah_count: 22,  revelation_place: 'makkah' },
  { number: 86,  name_arabic: 'الطارق',        name_english: 'At-Tariq',       name_urdu: 'الطارق',        ayah_count: 17,  revelation_place: 'makkah' },
  { number: 87,  name_arabic: 'الأعلى',        name_english: 'Al-Ala',         name_urdu: 'الأعلى',        ayah_count: 19,  revelation_place: 'makkah' },
  { number: 88,  name_arabic: 'الغاشية',       name_english: 'Al-Ghashiyah',   name_urdu: 'الغاشيہ',       ayah_count: 26,  revelation_place: 'makkah' },
  { number: 89,  name_arabic: 'الفجر',         name_english: 'Al-Fajr',        name_urdu: 'الفجر',         ayah_count: 30,  revelation_place: 'makkah' },
  { number: 90,  name_arabic: 'البلد',         name_english: 'Al-Balad',       name_urdu: 'البلد',         ayah_count: 20,  revelation_place: 'makkah' },
  { number: 91,  name_arabic: 'الشمس',         name_english: 'Ash-Shams',      name_urdu: 'الشمس',         ayah_count: 15,  revelation_place: 'makkah' },
  { number: 92,  name_arabic: 'الليل',         name_english: 'Al-Layl',        name_urdu: 'الليل',         ayah_count: 21,  revelation_place: 'makkah' },
  { number: 93,  name_arabic: 'الضحى',         name_english: 'Ad-Duha',        name_urdu: 'الضحى',         ayah_count: 11,  revelation_place: 'makkah' },
  { number: 94,  name_arabic: 'الشرح',         name_english: 'Ash-Sharh',      name_urdu: 'الشرح',         ayah_count: 8,   revelation_place: 'makkah' },
  { number: 95,  name_arabic: 'التين',         name_english: 'At-Tin',         name_urdu: 'التين',         ayah_count: 8,   revelation_place: 'makkah' },
  { number: 96,  name_arabic: 'العلق',         name_english: 'Al-Alaq',        name_urdu: 'العلق',         ayah_count: 19,  revelation_place: 'makkah' },
  { number: 97,  name_arabic: 'القدر',         name_english: 'Al-Qadr',        name_urdu: 'القدر',         ayah_count: 5,   revelation_place: 'makkah' },
  { number: 98,  name_arabic: 'البينة',        name_english: 'Al-Bayyinah',    name_urdu: 'البينہ',        ayah_count: 8,   revelation_place: 'madinah' },
  { number: 99,  name_arabic: 'الزلزلة',       name_english: 'Az-Zalzalah',    name_urdu: 'الزلزلہ',       ayah_count: 8,   revelation_place: 'madinah' },
  { number: 100, name_arabic: 'العاديات',      name_english: 'Al-Adiyat',      name_urdu: 'العاديات',      ayah_count: 11,  revelation_place: 'makkah' },
  { number: 101, name_arabic: 'القارعة',       name_english: 'Al-Qariah',      name_urdu: 'القارعہ',       ayah_count: 11,  revelation_place: 'makkah' },
  { number: 102, name_arabic: 'التكاثر',       name_english: 'At-Takathur',    name_urdu: 'التكاثر',       ayah_count: 8,   revelation_place: 'makkah' },
  { number: 103, name_arabic: 'العصر',         name_english: 'Al-Asr',         name_urdu: 'العصر',         ayah_count: 3,   revelation_place: 'makkah' },
  { number: 104, name_arabic: 'الهمزة',        name_english: 'Al-Humazah',     name_urdu: 'الھمزہ',        ayah_count: 9,   revelation_place: 'makkah' },
  { number: 105, name_arabic: 'الفيل',         name_english: 'Al-Fil',         name_urdu: 'الفيل',         ayah_count: 5,   revelation_place: 'makkah' },
  { number: 106, name_arabic: 'قريش',          name_english: 'Quraysh',        name_urdu: 'قريش',          ayah_count: 4,   revelation_place: 'makkah' },
  { number: 107, name_arabic: 'الماعون',       name_english: 'Al-Maun',        name_urdu: 'الماعون',       ayah_count: 7,   revelation_place: 'makkah' },
  { number: 108, name_arabic: 'الكوثر',        name_english: 'Al-Kawthar',     name_urdu: 'الكوثر',        ayah_count: 3,   revelation_place: 'makkah' },
  { number: 109, name_arabic: 'الكافرون',      name_english: 'Al-Kafirun',     name_urdu: 'الكافرون',      ayah_count: 6,   revelation_place: 'makkah' },
  { number: 110, name_arabic: 'النصر',         name_english: 'An-Nasr',        name_urdu: 'النصر',         ayah_count: 3,   revelation_place: 'madinah' },
  { number: 111, name_arabic: 'المسد',         name_english: 'Al-Masad',       name_urdu: 'المسد',         ayah_count: 5,   revelation_place: 'makkah' },
  { number: 112, name_arabic: 'الإخلاص',       name_english: 'Al-Ikhlas',      name_urdu: 'الإخلاص',       ayah_count: 4,   revelation_place: 'makkah' },
  { number: 113, name_arabic: 'الفلق',         name_english: 'Al-Falaq',       name_urdu: 'الفلق',         ayah_count: 5,   revelation_place: 'makkah' },
  { number: 114, name_arabic: 'الناس',         name_english: 'An-Nas',         name_urdu: 'الناس',         ayah_count: 6,   revelation_place: 'makkah' },
];

export function getSurahMeta(n: number): SurahMetaEntry | undefined {
  if (n < 1 || n > 114) return undefined;
  return SURAH_META[n - 1];
}
